#!/bin/sh

alias nv='nvim'
alias b='byobu'

alias ll='ls -lF'
alias la='ls -aF'
alias lla='ls -laF'

alias sd='sudo docker'

#----------- git -----------#
alias g='git'
alias gaa='git add --all'
alias gst='git status'
alias gcim='git commit -m'
alias gb='git branch'

# alias lvim='nvim -u ~/.local/share/lunarvim/lvim/init.lua --cmd "set runtimepath+=~/.local/share/lunarvim/lvim"'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -riv"
alias mv='mv -iv'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias makedir='makedir -vp'
