#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

# add link file folder to PATH
export PATH="/home/etg/.local/bin:$PATH"



#---------------------- fzf variables ---------------------
# config FZF
# if type rg &> /dev/null; then
  # export FZF_DEFAULT_COMMAND='rg --files --color=never --hidden'
  # export FZF_DEFAULT_OPTS='-m'
# fi

export FZF_DEFAULT_COMMAND='fd --type f --color=never --hidden'
# export FZF_DEFAULT_OPTS='-m --no-height'
export FZF_DEFAULT_OPTS='--no-height --color=bg+:#343d46,gutter:-1,pointer:#ff3c3c,info:#0dbc79,hl:#0dbc79,hl+:#23d18b'

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :50 {}'"

export FZF_ALT_C_COMMAND='fd --type d . --color=never --hidden'
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -50'"


#---------------------- add http and https proxy for shell ----------------------
alias proxy="export http_proxy=http://127.0.0.1:7890;export https_proxy=https://127.0.0.1:7890"
alias unproxy="unset http_proxy;unset https_proxy"








